### ISSUE TITLE
Cambios a métodos de petición API REST

### ISSUE THREAD

**Issue by SrHeli0s** [UNIZAR-30226-2022-07/Deploy#1]
La API actualmente esta usando métodos GET para realizar register y login.
La petición que se debe mandar a la API debe contener los datos del usuario (Ej: nombre y contraseña). Una petición GET no puede tener un body, por lo que debemos codificar los datos de la petición en la url (Ej: direccion.com/?user="Helios"&password="test1234" )
Aparte de ser altamente inseguro al mostrar datos sensibles, no tiene mucho sentido y nos supone una carga de trabajo considerable a @viictorgallardo y a mi en la implementación de frontend-web debido a limitaciones del framework Angular.

Sugiero el cambio de estos métodos a POST, donde podemos adjuntar un cuerpo fácilmente, aportar consistencia a la API y seguir las recomendaciones del standard.

Estoy al corriente de que, originalmente en la primera versión de la api, estos métodos iban a ser POST. Ruego la reconsideración de estas decisiones. 
Como siempre, estoy abierto a otras sugerencias y debate sobre el tema.

(Source: Especificacion [protocolo HTTP actual](https://www.ietf.org/rfc/rfc2616.txt), apartado 15.1.3)

**Comment by cborjamoreno** [comment]
Tenía entendido que el método POST era el que no permitía un body y era obligatorio incluir los datos en la petición. Parece que me confundí. Lo cambiamos a POST
